### ISSUE TITLE
12 Issues in SnapKit Dependencies

### ISSUE THREAD

**Issue by santoshn547** [Daltron/NotificationBanner#81] opened 2018-01-10 08:47 UTC
Installed pod 'NotificationBannerSwift'. 
I Got All This Errors I have Attached ScreenShots Of All errors Below.
Have Used Used NotificationBannerSwift before as well but never got such errors please Resolve Issues ASAP So I can Use this Awesome Notification Banner soon.

![screen shot 2018-01-10 at 2 09 53 pm](https://user-images.githubusercontent.com/26603675/34763225-5e971780-f610-11e7-9536-bbe37beaad83.png)
![screen shot 2018-01-10 at 2 10 29 pm](https://user-images.githubusercontent.com/26603675/34763226-5ed08d08-f610-11e7-9f92-1afbdfb5b2fe.png)
![screen shot 2018-01-10 at 2 11 17 pm](https://user-images.githubusercontent.com/26603675/34763227-5f089220-f610-11e7-94d0-d17143606f5b.png)
![screen shot 2018-01-10 at 2 11 43 pm](https://user-images.githubusercontent.com/26603675/34763228-5f40859a-f610-11e7-8be5-ed69e55c056f.png)
![screen shot 2018-01-10 at 2 12 11 pm](https://user-images.githubusercontent.com/26603675/34763229-5f90c4ce-f610-11e7-9551-dfd429955178.png)
![screen shot 2018-01-10 at 2 12 33 pm](https://user-images.githubusercontent.com/26603675/34763230-5fe20942-f610-11e7-813f-311298c5ca62.png)

**Comment by Daltron** [comment] 2018-01-10 14:01
Hi @santoshn547! 😄 This doesn't look like an issue on NotificationBanner's end. Is your project built in Swift 3 or Swift 4? Either way, go ahead and show me what your Podfile looks like and I'll try to help you out further 👍

**Comment by santoshn547** [comment] 2018-01-11 06:08
My Project is in Swift 3.
When I remove Notification Banner pod I don't get Any errors.
The Errors are in dependency of Banner Pod.
I have attached pod screenshot.
Help me out.

**Comment by Daltron** [comment] 2018-01-11 14:31
@santoshn547 So the problem is you are trying to compile a Swift 4 Pod into a Swift 3 project. You have two options:

1. You can point to the NotificationBanner pod version before it was committed to Swift 4
2. Your post install method should look like this:

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['NotificationBannerSwift', 'SnapKit', 'MarqueeLabel'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```

**Comment by patilkun** [comment] 2018-01-12 10:55
I am also getting same issue as @santoshn547 . I have Swift 4 project and Podfile looks like below.

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'NotificationBannerSwift'

  # Pods for TestApp

  target 'TestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```


Steps to reproduce the issue -

Create a dummy Swift iOS project using Xcode 9.1
From terminal go to the project folder.
Run `pod init` command
Change Podfile in project to look like above file
Run `pod install` command

Try to run the app and you will see all the errors that @santoshn547 mentioned.
When we run `pod install` command its fetching 1.4.2 version of NotificationBannerSwift which I guess is not the latest version

Below is the output of `pod install`

-----------

Analyzing dependencies
Downloading dependencies
Installing MarqueeLabel (3.1.2)
Installing NotificationBannerSwift (1.4.2)
Installing SnapKit (3.2.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `TestApp.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.

------

Thanks,
Kunal

**Comment by santoshn547** [comment] 2018-01-12 14:32
Using NotificationBannerSwift 1.4.4 version Solved my Issues.
Thanks For Help @Daltron

**Comment by Daltron** [comment] 2018-01-12 14:35
@patilkun I just did the steps as you said and encountered no problems. It sounds like your CocoaPods repo is out of date. Try running `pod repo update` and then do those steps again and see if you encounter any errors.

**Closed by Daltron** 2018-01-12 14:35 UTC

**Comment by patilkun** [comment] 2018-01-15 07:42
`pod repo update` fixed the issue for me. Thanks @Daltron
