### ISSUE TITLE
FloatingNotificationBanner missing on recently release 2.4.0?

### ISSUE THREAD

**Issue by rigaldamez** [Daltron/NotificationBanner#216] opened 2019-07-15 02:03 UTC
Hi,

regarding #213 

![image](https://user-images.githubusercontent.com/29295300/61192547-4288bf80-a6f4-11e9-82b3-52664eed1085.png)

**Comment by Daltron** [comment] 2019-07-15 02:48
Hi @rigaldamez! :smile I plan on fixing this tomorrow. Sorry for the inconvenience. Stay tuned!

**Comment by Daltron** [comment] 2019-07-15 14:37
This has been fixed in the 2.4.1 Cocoapods release!

**Closed by Daltron** 2019-07-15 14:37 UTC

**Comment by rigaldamez** [comment] 2019-07-16 00:51
thanks Daltron, how can I load a custom view within `FloatingNotificationBanner`?

![image](https://user-images.githubusercontent.com/29295300/61258162-6eb74580-a7b3-11e9-8dcd-36370c784773.png)

**Comment by Daltron** [comment] 2019-07-16 01:17
That currently isn't possible as `FloatingNotificationBanner` doesn't inherit from `NotificationBanner` which is the only class that supports custom views. This definitely needs to be added though. I have created an [issue](https://github.com/Daltron/NotificationBanner/issues/217) to track this.

**Comment by Daltron** [comment] 2019-07-17 14:16
@rigaldamez, this can now be found in the `2.5.0` CocoaPods release!

**Comment by rigaldamez** [comment] 2019-07-22 01:04
finally got a chance to test this and its not working for me... do I need to set the corner radius? 

```
let banner = FloatingNotificationBanner(customView: myCustomView)
banner.show()
```

**Comment by Daltron** [comment] 2019-07-22 13:25
You will need to set the `cornerRadius` when calling the `show()` method like so: `show(cornerRadius: 10)`

**Comment by rigaldamez** [comment] 2019-07-22 23:40
I'm scratching my head, this is my code and the output is still square corners?

![image](https://user-images.githubusercontent.com/29295300/61672086-76359c00-ad29-11e9-8b0c-a3e3d930510f.png)

![image](https://user-images.githubusercontent.com/29295300/61672161-bd239180-ad29-11e9-8a47-791b8f22c88d.png)

**Comment by Daltron** [comment] 2019-07-23 01:54
<img width="414" alt="Screen Shot 2019-07-22 at 3 53 58 PM" src="https://user-images.githubusercontent.com/9689335/61676796-dba27200-acc2-11e9-9a32-5890e9736265.png">
Can you show me what your custom view consists of and how you are initializing it. I'm not seeing any issues.

**Comment by rigaldamez** [comment] 2019-07-23 03:46
Initialising `myCustomView` and displaying using `FloatingNotificationBanner`

```
let imageData:NSData = NSData(contentsOf: imageUrl)!
                                
                                DispatchQueue.main.async {
                                    
                                    let image = UIImage(data: imageData as Data)
                                    
                                    let myCustomView = NotificationBannerReply()
                                    
                                    myCustomView.contentView.backgroundColor = #colorLiteral(red: 0.8745098039, green: 0.3019607843, blue: 0.4117647059, alpha: 1)
                                    myCustomView.clinkBtnView.isHidden = false
                                    
                                    myCustomView.userSelectedId = toId
                                    myCustomView.venueId = venueId
                                    myCustomView.nameLbl.text = name
                                    myCustomView.profileImg.image = image
                                    myCustomView.messageLbl.text = "Acknowledged your compliment"
                                    
                                    //Banner
                                    let banner = FloatingNotificationBanner(customView: myCustomView)
                                    
                                    banner.autoDismiss = false
                                    banner.dismissOnTap = true
                                    banner.dismissOnSwipeUp = true
                                    
                                    banner.show(cornerRadius: 10)
                                    
                                    //Then remove from firebase once banner message has been shown
                                    let ref = self.REF_USERS_COMPLIMENTS_ACK.child(uid).child(complimentId)
                                    ref.removeValue()
                                    
                                }//end DispatchQueue.main.async
```

This is my `NotificationBannerReply`

```
class NotificationBannerReply: UIView {
    
    
    @IBOutlet var contentView: UIView!
    @IBOutlet weak var profileImg: CircleImage!
    @IBOutlet weak var nameLbl: UILabel!
    @IBOutlet weak var messageLbl: UILabel!
    @IBOutlet weak var clinkBtnView: DropShadowCircleView!
    
    var userSelectedId: String?
    var venueId: String?

    //taptic
    let tapticGenerator = UINotificationFeedbackGenerator()
    
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        loadViewFromXib()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        loadViewFromXib()
    }
    
    func loadViewFromXib() {
        
        Bundle.main.loadNibNamed("NotificationBannerReply", owner: self, options: nil)
        addSubview(contentView)
        contentView.frame = self.bounds
        contentView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        
    }
}

```

**Comment by Daltron** [comment] 2019-07-24 13:22
I believe the problem is your loading your contentView from a xib and adding it as a subview. There is no workaround for this right now. You will need to set the cornerRadius of the contentView yourself in the xib or via code in this class. It should work then. 👍

**Comment by rigaldamez** [comment] 2019-07-24 23:13
that worked!

Thanks so much for your support and for the great work you've put in to make this library available for us learners to use :)
