### ISSUE TITLE
New version 1.4.5 is crashing in my app

### ISSUE THREAD

**Issue by balrajOla** [Daltron/NotificationBanner#52] opened 2017-09-21 07:04 UTC
<img width="882" alt="screen shot 2017-09-21 at 12 33 40 pm" src="https://user-images.githubusercontent.com/12622119/30682949-2268afb0-9ec9-11e7-932d-0b4cb7ea4bd0.png">

Please help

**Comment by Daltron** [comment] 2017-09-21 12:40
Hi @balrajOla! I'm going to need a little bit more information. Are you able to cosistently reproduce? Also, it looks like that line is a breakpoint, not a crash. Any further details would be helpful!

**Comment by Daltron** [comment] 2017-09-24 03:20
Going to close this as I do believe the issuer was confusing the breakpoint for a crash.

**Closed by Daltron** 2017-09-24 03:20 UTC
