### ISSUE TITLE
SnapKit v4 for Swift 4

### ISSUE THREAD

**Issue by FunProject** [Daltron/NotificationBanner#53] opened 2017-09-23 13:41 UTC
Hello,
Please update SnapKit dependency to v4.0 to be Swift 4.x and iOS 11 compatible.
Right now I cannot build the app.
Thanks

**Comment by Daltron** [comment] 2017-09-23 15:32
Duplicate of #51

**Closed by Daltron** 2017-09-23 15:32 UTC

**Comment by Daltron** [comment] 2017-09-24 03:17
@FunProject Swift 4 support is now available in [v1.5.0](https://github.com/Daltron/NotificationBanner/releases/tag/1.5.0) release! 🎉

**Comment by FunProject** [comment] 2017-09-24 10:16
Great! Thanks 👍
