### ISSUE TITLE
StatusBarNotificationBanners label moves to right corner on orientation change. 

### ISSUE THREAD

**Issue by aman836** [Daltron/NotificationBanner#330] opened 2020-11-24 14:26 UTC
My app does not support landscape mode and still if the user tilts their phone in any direction the label inside the StatusBarNotificationBanners moves itself from the centre to the right corner of the banner. 

The banner does not have more than 2 words at any given time and this is how it is being initialised
StatusBarNotificationBanner(title: "Connecting...", style: .warning)

Pod version 3.0.2
The issue can be reproduced on any device with iOS 12 and above.

**Comment by Szymon-Gesicki** [comment] 2020-11-24 20:16
+1

**Comment by aman836** [comment] 2020-12-09 12:09
Hey Guys, 
It's been a while, does anyone have a solution for this. 

Thanks in advance.

**Comment by Daltron** [comment] 2020-12-10 22:03
@aman836 Could you provide a video/gif of what you are experiencing please along with the code snippet you are using to show the banner? I'm not able to reproduce the issue currently.

**Comment by aman836** [comment] 2020-12-15 10:31
@Daltron Thank you for responding, please find the code snippet and GIF attached below. 😊

`
private var banner: StatusBarNotificationBanner? = nil
func updateBanner(withStatus status: String) {
        switch status {
        case "connected":
            banner?.dismiss()
            banner = StatusBarNotificationBanner(title: "You're back on!", style: .success)
            banner?.show()
        case "connecting":
            banner?.dismiss()
            banner = StatusBarNotificationBanner(title: "Connecting...", style: .warning)
            banner?.autoDismiss = false
            banner?.show()
        case "disconnected":
            banner?.dismiss()
            banner = StatusBarNotificationBanner(title: "You are offline", style: .danger)
            banner?.autoDismiss = false
            banner?.show()
        case "notConnected":
            banner?.dismiss()
            banner = StatusBarNotificationBanner(title: "You are offline", style: .danger)
            banner?.autoDismiss = false
            banner?.show()
        case "syncing":
            banner?.dismiss()
            banner = StatusBarNotificationBanner(title: "Syncing...", style: .info)
            banner?.autoDismiss = false
            banner?.show()
        default:
            break
        }
    }
`

![IMG_0006 TRIM](https://user-images.githubusercontent.com/56108102/102202913-e8de8300-3eed-11eb-9876-bfca2461602b.gif)

**Comment by Daltron** [comment] 2020-12-17 03:00
Hi @aman836! Thanks for providing the GIF. Is there any way you could provide me a demo project to download that showcases this behavior? As is currently, I am unable to reproduce.

**Comment by Daltron** [comment] 2020-12-17 03:26
Thanks for the GIF @aman836! I was able to reproduce the issue and this should now be fixed in the 3.0.6 release! Thank you for reporting this!

**Closed** 2020-12-17 03:26 UTC
